### ISSUE TITLE
Is it possible to add extra fields to individual logs?

### ISSUE THREAD

**Issue by nickbroon** [lunaryorn/systemd-journal-logger.rs#6]
`systemd_journal_logger::init_with_extra_fields()` allows adding extra fields to every log message.

But is there a way to add extra fields to just individual log messages?

Perhaps something like: `info!("Hello systemd journal"; "FOO" => "BAR");`

**Comment by lunaryorn** [comment]
The logger writes structured log data to the journal.  That's an unstable feature if the log crate, see the log crate's GitHub for details.  

I don't know whether there's syntax support in the log macros already.  

For more info please refer to the log crate for more information.

**Comment by nickbroon** [comment]
ah, thanks for the pointer.
I've found https://github.com/rust-lang/log/issues/343 which tracks adding key/value pairs to the log crate macros.
